version: '3'

services:
  main_app:
    build:
      context: ./main_app
    ports:
      - "5000:5000"
    volumes:
      - ./main_app:/app
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5000

  vulnerable_lab:
    build:
      context: ./vulnerable_lab
    ports:
      - "5001:5001"
    volumes:
      - ./vulnerable_lab:/app
